#!/usr/bin/env node
// packages/manifest-kit/scan-routes.js — generate the route list at build time
//
// Walks a Next.js app directory and writes routes.generated.ts. Run it in
// prebuild so the manifest can never drift from what the app actually serves —
// a hand-maintained route list is wrong within a week.
//
// Usage: node scan-routes.js <appDir> <outFile>
// CR AudioViz AI, LLC · EIN 39-3646201
const fs = require('fs')
const path = require('path')

const appDir = process.argv[2] || 'app'
const out = process.argv[3] || 'lib/manifest-kit/routes.generated.ts'

const routes = []
const apiRoutes = []

function walk(dir, base = '') {
  let entries
  try { entries = fs.readdirSync(dir, { withFileTypes: true }) } catch { return }
  for (const e of entries) {
    const full = path.join(dir, e.name)
    if (e.isDirectory()) {
      // Route groups (parens) do not appear in the URL.
      const seg = e.name.startsWith('(') && e.name.endsWith(')') ? '' : '/' + e.name
      walk(full, base + seg)
      continue
    }
    if (e.name === 'page.tsx' || e.name === 'page.ts' || e.name === 'page.jsx') {
      routes.push(base || '/')
    }
    if (e.name === 'route.ts' || e.name === 'route.js') {
      apiRoutes.push(base || '/')
    }
  }
}
walk(appDir)

const body = `// GENERATED by manifest-kit/scan-routes.js — do not edit.
// Regenerated on every build, so the manifest cannot drift from what ships.
// ${new Date().toISOString()}

export const ROUTES: string[] = ${JSON.stringify(routes.sort(), null, 2)}

export const API_ROUTES: string[] = ${JSON.stringify(apiRoutes.sort(), null, 2)}
`
fs.mkdirSync(path.dirname(out), { recursive: true })
fs.writeFileSync(out, body)
console.log(`  ${routes.length} pages, ${apiRoutes.length} api routes -> ${out}`)
